name: intake-df-cat-test
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - intake>=0.7
  - intake-esm
  - itables
  - polars>=1.12
  - pytest
  - pip
  - pip:
    - build
    - ruff
    - codecov
    - pre-commit
    - pytest-cov
    - twine
